### ISSUE TITLE
Assets 

### ISSUE THREAD

**Issue by ghaiyur-musubi** [Tech-i-s/techis-python-probation#2]
![image](https://user-images.githubusercontent.com/67789350/114799843-37296300-9db6-11eb-9053-7baea859afba.png)

**Comment by moetokitai** [comment]
<img width="835" alt="Screen Shot 2021-06-30 at 3 56 56" src="https://user-images.githubusercontent.com/59639763/123875967-2f5e7100-d958-11eb-945c-c7b310279ac6.png">
